import type { Metadata } from "next";
import "@/app/[locale]/globals.css";
import AdminLayout from "@/components/layout/AdminLayout";

export const metadata: Metadata = {
  title: "My Company | Home",
  description: "Generated by create next app",
};

export default function BackOfficeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body cz-shortcut-listen="true">
        <AdminLayout>{children}</AdminLayout>
      </body>
    </html>
  );
}
